import NavBar from '../components/NavBar'
import '../css/globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html  data-theme="night" lang="en">
      <body>
      <NavBar/>
        {children}
        </body>
    </html>
  )
}
